### ISSUE TITLE
Supervised Learning

### ISSUE THREAD

**Issue by VirtualAI** [simontomaskarlsson/CycleGAN-Keras#15]
Hello, 
sorry to bother you again. Is it possible to use supervised learning (e.g. paired images) but small dataset and combine it with large unpaired/ unsuperwised learning? Thanks in adventage

PS: or how else is the supervised setting ment e.g what does it do? I only know supervised for example with paired datasets

**Comment by simontomaskarlsson** [comment]
Hi again @VirtualAI,

No worries at all, I always answer when I have time over.
The supervised training setting is, just as you say, meant to be used with paired data. What you can do is to first train in a supervised manner with the paired data, and then train the same model again with unpaired data by loading the newly trained model before beginning.

You can load a model using Keras, see the method `load_model_and_weights` on line 819 in model.py as an example.

**Comment by VirtualAI** [comment]
Hello, thank you very much :)
