### ISSUE TITLE
Error when batch size > 1

### ISSUE THREAD

**Issue by kpagels** [simontomaskarlsson/CycleGAN-Keras#21]
Hi Simon,

I like your implementation and am really thrilled that you implemented it in Keras, so thanks for that!

I have an suggestion for your code. I changed the batch_size to 16 and a problem occurred in the following place:

	for loop_index in range(0, epoch_iterations, batch_size):
		if loop_index + batch_size >= min_nr_imgs:

Lets say my dataset has 100 images which means min_nr_imgs is 100. The problem occurs when loop_index is 96 and  loop_index + batchsize > min_nr_imgs.

 loop_index + batchsize = 96 + 16 = 110 which is bigger then 100.

	indexes_B = random_order_B[loop_index: loop_index + batch_size]

Now the order will be 96: 110 which is out of range because my array size was only 100. One suggestion could be to change it to the following: 

	indexes_B = random_order_B[min_nr_imgs - batch_size: min_nr_imgs]

Kind Regards,

**Comment by simontomaskarlsson** [comment]
Hi @kpagels,

Thank you for the appreciation and the suggested update. I see the problem, please create a pull request and I will approve it.

Regards,
Simon

**Comment by kpagels** [comment]
Ok ill do that tomorrow.
