### ISSUE TITLE
Save cycle_loss to training_history?

### ISSUE THREAD

**Issue by kpagels** [simontomaskarlsson/CycleGAN-Keras#23]
Hi,

Do you know how I can save cycle_loss in the training_history? As far as I can see, it is not saved.

**Comment by simontomaskarlsson** [comment]
Hi,
The cycle loss as in the loss of the reconstruction? Maybe I'm misunderstanding you.

**Comment by kpagels** [comment]
Ah you are right. Its actually saved and called "reconstruction loss". I missunderstood the name because it was not called "Cycle loss". Thanks! :)
