### ISSUE TITLE
Why such small batch size is used

### ISSUE THREAD

**Issue by swang423** [simontomaskarlsson/CycleGAN-Keras#9]
Not so much an issue but more of an inquiry. Why is such small batch size used? Have you tried larger batch sizes? Since small batch size slows down training drastically. Thanks

**Comment by simontomaskarlsson** [comment]
Hi @swang423,

During my research I found the small batch size to give the best results, however only minor evaluations were made.

The original CycleGan paper might have some discussion around the batch size, I at least believe they have good reason for using batch size 1. From my evaluations this gave the best results also.

I do agree though that a larger batch size with faster training is better if the results are as good.

**Comment by swang423** [comment]
Thanks.  In your research, do you apply it to a different data set? If so, could you share what parameters you might need to change to tune the cycleGAN?

**Comment by simontomaskarlsson** [comment]
Yes, a few different datasets where used and a bunch of different parameter settings for research purposes. For the CycleGan the best results where most often with the default parameters, i.e. the ones used in the original CycleGan implementation.

Parameter tuning is perhaps the hardest part of deep learning development so there is no straight answer here. What you need to do is to look at how the different losses change during training, as well as the results, and try and draw conclusions as to what to try next. I tried building this model to make is easy to modify many different learning and model settings together ways to examine the different losses are also included in 'plotCSVfile.py'.
